### ISSUE TITLE
Error while model training start

### ISSUE THREAD

**Issue by marlon-br** [vlomme/MelGan-WavGan#2]
When I try to make training I get the error (I added torch.autograd.set_detect_anomaly(True) to get more details):

```
Загрузка чекпоинтов
Чекпоинт загружен: Эпоха 298, Шаг 518000
Warning: Error detected in WeightNormCudaInterfaceBackward. Traceback of forward call that caused the error:
  File "melgan.py", line 204, in <module>
    train()
  File "melgan.py", line 114, in train
    d_fake = D(fake_audio.cuda())
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/MelGan-WavGan/utils.py", line 278, in forward
    result.append(module(x))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/MelGan-WavGan/utils.py", line 259, in forward
    x = module(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 542, in __call__
    result = hook(self, input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/utils/weight_norm.py", line 55, in __call__
    setattr(module, self.name, self.compute_weight(module))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/utils/weight_norm.py", line 18, in compute_weight
    return _weight_norm(v, g, self.dim)
 (print_stack at /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:60)
Traceback (most recent call last):
  File "melgan.py", line 204, in <module>
    train()
  File "melgan.py", line 154, in train
    g_loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 3]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

Maybe I need to install correct pytorch version or there is some other issue with inplace variables. Was not able to address the issue.

In my experiment I just call
`python melgan.py -r t -f mel`

**Comment by vlomme** [comment]
I'm not sure, but you can try to fix it here
```
fake_audio = G(mel).cuda()
d_fake_detach = D(fake_audio.detach())
d_fake = D(fake_audio)
```

**Comment by marlon-br** [comment]
Actually I moved `d_fake = D(fake_audio.cuda())` to the generator section, like it advised there: https://stackoverflow.com/a/62147652/2260921. Now training moves forward. Thanks

```
# ---------------Генератор----------------------
# Считаем ошибку на отклик созданного сигнала с градиентом
            
d_fake = D(fake_audio.cuda())
```
